# Starter pipeline
# minimal pipeline that you can customize to build and deploy your code.

trigger:
  branches:
    include:
    - master
    - releases/*
    exclude:
    - releases/old*

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: job1
  steps: 
  - script: echo Hi DevOps
    displayName: 'One line to execute'
  - script: echo Azure-DevOps.. is interesting!
    displayName: 'Run a one-line script'

- job: Job2
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
