trigger:
  branches:
    include:
    - master
    - releases/*
    exclude:
    - releases/old*
pool:
  vmImage: 'ubuntu-latest'
  
stages:
- stage: Build
  jobs:
  - job: first_build_job
    steps:
    - bash: echo This is build stage
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.Id)
    - bash: echo $(Build.Reason)
    - bash: echo $(Build.ContainerId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(agent.OS)
    - bash: echo $(agent.Name)
    - bash: echo $(agent.WorkFolder)
    - bash: echo $(agent.Id)
    - bash: echo $(System.HostType)
    - bash: echo $(System.JobAttempt)
    - bash: echo $(environment.Name)
    


- stage: Dev_Deploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: Code_deploy_Dev_env
    steps: 
    - bash: echo Hello from Dev environment


# - stage: QA_deploy
#   jobs:
#   - job: QA_build
#     steps: 
#     - bash: echo hello from QA environment
  

# - stage: Production_deploy
#   dependsOn: 
#   - Dev_Deploy
#   - QA_deploy
#   jobs:
#   - job: Product_go_live
#     steps: 
#     - bash: echo Hello from End users 
