trigger:
  branches:
    include:
    - master
    - releases/*
    exclude:
    - releases/old*

pool:
  vmImage: 'ubuntu-latest'
  
stages:
- stage: Build
  jobs:
  - job: first_build_job
    steps:
    - bash: echo Running on the $(operatingSystem)
    - bash: echo This is build stage
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.Id)
    - bash: echo $(Build.Reason)
    - bash: echo $(Build.ContainerId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(agent.OS)
    - bash: echo $(agent.Name)
    - bash: echo $(agent.WorkFolder)
    - bash: echo $(agent.Id)
    - bash: echo $(System.HostType)
    - bash: echo $(System.JobAttempt)
    - bash: echo $(environment.Name)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
         **/*.yaml
         **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Dev_Deploy
  jobs:
  - deployment: DevDeploy
    environment: Dev
    strategy:
      runOnce: 
        deploy:
          steps:
          - script: echo deploy to dev

- stage: QA_Deploy
  jobs:
  - deployment: QADeploy
    environment: QA
    strategy:
      runOnce: 
        deploy:
          steps:
          - script: echo deploy to QA



# - stage: QA_deploy
#   jobs:
#   - job: QA_build
#     steps: 
#     - bash: echo hello from QA environment
  

# - stage: Production_deploy
#   dependsOn: 
#   - Dev_Deploy
#   - QA_deploy
#   jobs:
#   - job: Product_go_live
#     steps: 
#     - bash: echo Hello from End users 
